config/routes.rb
Rails.application.routes.draw do

  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'homes#index'
  
  resources :homes do
    collection do
      get 'homepage'
      #get 'about_us'
      get 'faq'
      get 'terms_and_conditions'
      get 'products'
    #  get 'flour'
      get 'contact_us'
      get 'concept'
     # get 'receipies'
      get 'facts'
      get 'historic_value'
     # get 'see_more_details'
      get 'product_popup'
      get 'testimonial'
      post :create_testimonial
    end
  end

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :checkouts, only: [:shipping, :billing] do
    collection do
      get :shipping
      get :billing
    end
  end

  #root to: "products#index"
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <span class="logo">LOGO</span>
      </div>
      
      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="menu">
          <span>Support</span>    
          <li>
            <a href="/homes/terms_and_conditions">Terms & Condition</a>
          </li>
               
          <li>
             <a href="/homes/homepage">Shipping & Return </a>
          </li>
               
          <li>
            <a href="/homes/faq">Faq</a>
          </li>
               
          <li>
             <a href="/homes/contact_us">Contact us </a>
          </li>
        </ul>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="address">
          <span>Contact</span>       
          <li>
             <i class="fa fa-phone" aria-hidden="true"></i> <a href="#">Phone</a>
          </li>
          <li>
             <i class="fa fa-map-marker" aria-hidden="true"></i> <a href="#">Adress</a>
          </li> 
          <li>
             <i class="fa fa-envelope" aria-hidden="true"></i> <a href="#">Email</a>
          </li> 
          <span class="social text-left">
            <a class="no-margin" href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-google-plus"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
          </span>
        </ul>
      </div>
    </div> 
  </div>
</footer>



    <style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900');

body{
    font-family: 'Roboto', sans-serif;
}

.search-text{
	margin-top:50px;
	background-color: #272d33;
	padding-top:60px;
	padding-bottom:60px;
}
	
.search-text .input-search{
	height:45px;
	width:40%;
	padding-left:20px;
    color:#333;
} 

.search-text .btn-search{
    background: #da3e44;
    font-family:Roboto;
    border:none;
	color:#FFF;
	height: 45px;
    width: 80px;
}

.search-text h4{
    color: #FFF;
    font-weight: 700;
}

footer{
     background-color: #33383c;
     padding:30px 0px;
}	       

.logo{
    color:#FFF;
    font-weight:700;
    font-size:30px;
}

.address span , .menu span{
   color: #FFF; 
   font-weight: bold; 
   border-bottom: 1px solid #c7c7c7; 
   padding:10px 0px;
   display: block;
   text-transform: uppercase;
   font-size: 16px;
   letter-spacing: 3px;
}
 
.address li a , .menu li a{
    color:#FFF;
    letter-spacing: 3px;
    text-decoration:none;
    font-size:14px;
}

.address li, .menu li{
    margin:20px 0px;
    list-style: none;
}

.address li a:hover , .menu li a:hover{
    color: #da3e44;
    -webkit-transition: all 1s ease-in-out;
    -moz-transition: all 1s ease-in-out;
    -o-transition: all 1s ease-in-out;
    transition: all 1s ease-in-out;
}

.address .fa{
    color: #da3e44;
    margin-right: 10px;
    font-size:18px;
}

    </style>	

app/views/layouts/_header.html.erb
<div class="container"style="height:100%;width:100%;background-color:white;">
	<div class="row">
		<div class="col-lg-12">
			<div class="row">
				<div class="col-lg-3"><h1><a href="/homes/homepage" style="color:black;"><img src="/assets/undefined.jpg" style = "height:40px; width:140px;"></a></h1></div>
				<div class="col-lg-6">
					<br>
					<ul  class="nav nav-pills">
						<li>
						    <a style="color:black; size:20" href="/homes/homepage"><%=HeaderLink.all[0].title%></a>
						</li>
						
						<li class="dropdown">
							<a  href="/homes/concept" style="color:black; size:20"><%=HeaderLink.all[1].title%> </a>
						</li>
					    
					    <li class="dropdown"><a href="/homes/products" style="color:black; size:20"><%=HeaderLink.all[2].title%></a>
					    </li>

					    <li class="dropdown">
					    	<a href="/homes/facts" style="color:black; size:20"><%=HeaderLink.all[3].title%></a>
					    </li> 

					    <li class="dropdown">
					    	<a href="/homes/historic_value" style="color:black; size:20"><%=HeaderLink.all[4].title%></a>
					    </li> 

					    <li class="dropdown">
					    	<a href="/homes/homepage#home_testimonial" style="color:black; size:20" id="testimonial"><%=HeaderLink.all[5].title%></a>
					    </li> 	    
				  </ul>
				</div>
				<br>
				<%unless params["controller"].include?("devise")%>
					<div class="col-lg-1 col-lg-offset-1">
					<% if user_signed_in? %>
					  <p></p>
					  <%= link_to( destroy_user_session_path, method: :delete)  do %>
						  <span class="glyphicon glyphicon-log-out" style="color:black;"></span>
					  <% end %>
				  <% else %>
				    <p></p>
				    <%= link_to( new_user_session_path)  do %>
					    <span class="glyphicon glyphicon-user" style="color:black;"></span>
					  <% end %>  
				  <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp;
					<a href="/cart">
					  <% if(current_order.order_items.size > 0) %>
              <span class="cart-count"><%= current_order.order_items.size %></span>
            <% end %>
					  <span class="glyphicon glyphicon-shopping-cart" style="color:black;"></span>
					</a>
			    </div>
        <%end%>
			</div>		
		</div>
	</div>
</div>





<style>
	.dropdown:hover .dropdown-menu {
    display: block;
    margin-top: 0; // remove the gap so it doesn't close
	}
	.dropdown-menu > li > a:hover {
    color: #fff;
  background-color: orange;
  border-color: #fff;
    background-image: none;
}
	</style>
	

app/views/layouts/_home_page_slider.html.erb
<div class="bs-example">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>   
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <%SliderImage.all.each.with_index do |s, index|%>
                <%cla=  (index == 0) ? 'active' : ''%>
                <div class="item <%=cla%>">
                    <%=image_tag s.name.url, style: "height:400px; width:900px;"%>
                </div>
            <%end%> 
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            
        </a>
        <center><a class="btn btn-success" href="/homes/restro">Shop Now</a></center>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anndefined</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
  	<%unless params[:action] == "index"%>
  	  <%=render 'layouts/header'%>
    <%end%>  

    <%= render 'layouts/messages' %>
    <%= yield %>
    <% if params[:action] != "index" %>
      <%= render 'layouts/footer'%>
    <% end %>
  </body>
</html>

<style>
.loader {
  position: absolute;
  z-index: 1;
  width: 100%;
  height: 100%;
   -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
</style>


<style type="text/css">
.carousel{
    background: #2f4357;
    margin-top: 20px;
}
.carousel .item{
    min-height: 380px; /* Prevent carousel from being distorted if for some reason image doesn't load */
}
.carousel .item img{
    margin: 0 auto; /* Align slide image horizontally center */
}

</style>
</head>